name = "realkastien/reliability"
version = "0.0.5"
description = "A lightweight networking library with buffers, extremely friendly syntax and focused on giving you high control over your Remote behavior."
authors = ["realkastien", "Galvagniofc"]
repository = "https://github.com/realkastien/Reliability"
license = "MIT"

includes = [
  "pesde.toml",
  "README.md",
  "LICENSE",
  "src/**/*.luau",
]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }
