local module = require("./../../../../../../luau_packages/.pesde/0x5eal+unzip/0.1.0/unzip/lib/init")
export type ZipEntry  = module.ZipEntry 
export type MadeByOS  = module.MadeByOS 
export type CompressionMethod  = module.CompressionMethod 
export type ZipEntryProperties  = module.ZipEntryProperties 
export type UnixMode  = module.UnixMode 
export type ZipReader  = module.ZipReader 
export type ZipStatistics  = module.ZipStatistics 
return module